#!/bin/bash
set -euxo pipefail

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

mkdir -p ~/.config && rm -rf ~/.config/nvim && ln -s "$DIR/config/nvim" ~/.config/nvim
rm -rf ~/.vim && ln -s "$DIR/vim" ~/.vim
rm -f ~/.vimrc && ln -s "$DIR/vimrc" ~/.vimrc
rm -f ~/.zshrc && ln -s "$DIR/zshrc" ~/.zshrc

git submodule update --init --remote
