#!/bin/bash
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

rm -rf ~/.vim && ln -s "$DIR/vim" ~/.vim
rm -f ~/.vimrc && ln -s "$DIR/vimrc" ~/.vimrc
rm -f ~/.bash_aliases && ln -s "$DIR/bash_aliases" ~/.bash_aliases
